### ISSUE TITLE
Ethereal enforcer unkillable

### ISSUE THREAD

**Issue by LoneMekkAzulf40K** [LouisSilva/LethalCompanyHauntedHarpist#10]
Hello,
Doing my modpack and while i am testing fighting againts the Ethereals enforcers with Imperium, being alone or spawned by the Piper i found strange that they do take damage but never dies. I did check the config and they are supposed to be at 6 hp and the shield taking one hit only. (I even put it off just to be sure.)

On my case, the shield never dissapear or at random intervals, and the Ethereal can take 100 dmg without even flitching.
Harpist and Piper does dies as intended.

Here are the only logs that i managed to get, while hitting him with a shovel
![image](https://github.com/LouisSilva/LethalCompanyHauntedHarpist/assets/170327818/7918081d-2ac9-45ea-82b1-a9d7c500aa62)

Here is the code of the modpack that i use :
018fbcbf-4de3-a8f1-2fc4-47cc03b6d237

I am sorry to be unable to give you more information ^^'

Thanks in advance :)

**Comment by LouisSilva** [comment]
Fixed in the lastest update.
