### ISSUE TITLE
[Issue] 2 days no one test that? can't grab Bagpipes even u killed Phantom Piper

### ISSUE THREAD

**Issue by CoolLKKPS** [LouisSilva/LethalCompanyHauntedHarpist#9]
[Warning: Unity Log] Couldn't create a Convex Mesh from source mesh "Readable Bagpipes" within the maximum polygons limit (256). The partial hull will be used. Consider simplifying your mesh.

**Comment by CoolLKKPS** [comment]
@LouisSilva

**Comment by LouisSilva** [comment]
Thank you for the report, I'll look into it. As for the reason why its been 2 days and no one has said anything, is because the Phantom Piper is no where near as popular as the Haunted Harpist unfortunately :( , I don't think many people use him.

**Comment by CoolLKKPS** [comment]
uh well bc this issue should be can easily found bc im pretty sure many modpack authors are using this mod, they should receive some report about this issue, hmh maybe im reacting too strongly when this problem are happening
and btw, thx for the reply.

**Comment by LouisSilva** [comment]
In the newest update its fixed.
